services:
  - type: web
    name: dh2e-vtt-backend
    env: node
    rootDir: server
    plan: free
    buildCommand: "npm install"
    startCommand: "node src/server.js"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: file:./db.sqlite
